### ISSUE TITLE
Why is the feature list so small? Maybe move to Python?

### ISSUE THREAD

**Issue by afiaka87** [covercash2/ultron#8]
What is the point of this? bA1bot can do all this stuff already

`.address
.bio <optional_username>
.botinfo
.close <bet_topic> <correct_answer>
.color <optional_username>
.commands
.device
.etym
.favoriteshow <optional_username>
.firstname <optional_username>
.fortune (removed)
.gpt2
.gpt2c
.gpt2p
.help
.hometown <optional_username>
.joined <optional_username>
.joke
.lastname <optional_username>
.lastquote
.lastseen <optional_username>
.links <optional_username>
.live <optional_search>
.location <optional_username>
.magic8ball <yes_or_no_question>
.markov <nothing_or_something_from_list>
.markovlist
.memento
.name <optional_username>
.next <optional_tv|simulcast> <optional_search>
.open <bet_topic>
.play <youtube_or_direct_imgur_gfycat_link>
.postcount <optional_username>
.poster <optional_username>
.postsperday <optional_username>
.profile <optional_username>
.quote <number>
.quotesearch <search_query>
.quoteesearch <search_query>
.quotersearch <search_query>
.r <option_1> | <option_2> | <option_3>
.rand <option_1> | <option_2> | <option_3>
.random <option_1> | <option_2> | <option_3>
.rnn <optional_search>
.roll <eg_1d20_3d6>
.selfcount <search_string>
.selfrand
.selfrandgpt2c
.show <lowercase_show_title_with_hyphens>
.sites <optional_username>
.tr <thing_to_translate>
.ud <term_to_look_up>
.urls <optional_username>
.w <city_name>
.w <5_digit_zip_code>
.whatson <optional_tv|simulcast>
.wiki
.yt
`

The amazing developers were supposedly able to iterate _so_ fast _because_ they used the mythic "Python 3" to write it. Python 3 is web scale. 

Food for thought.

**Comment by covercash2** [comment]
Rust has zero-cost abstractions, move semantics, guaranteed memory safety, threads without data races, trait-based generics, pattern matching, type inference, minimal runtime and efficient C bindings.
